## Basic Configuration
baseurl = "/"
title = "DiabeticsBC"
theme = "hyde-hyde"
languageCode = "en"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

## Hugo Built-in Features
disqusShortname = "diabeticsbc"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

## Site Settings
[params]
    author = "Stuart Hertzog"
    description = "We Are People With Diabetes"
    authorimage = "/img/hugo.png"
    dateformat = "January 2, 2006"
    highlightjs = true
    # highlightjsstyle = "github"
    # please choose either GraphComment or Disqus
    # GraphCommentId = "your-graph-comment-id"

## Social Accounts
[params.social]
    # github = "<username>"
    # instagram = "<username>"
    # xing = "<username>"
    # linkedin = "<username>"
    # twitter = "diabeticsbc"
    facebook = "groups/diabeticsbc"
    # stackoverflow = "<username>"
    email = "info@diabeticsbc.ca"

## Main Menu
[[menu.main]]
    name = "Home"
    weight = 100
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Posts"
    weight = 200
    identifier = "posts"
    url = "/post/"
[[menu.main]]
    name = "Hugo"
    weight = 250
    identifier = "hugo"
    url = "/hugo/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
