## Basic Configuration
baseurl = "/"
title = "DiabeticsBC"
theme = "hyde-hyde"
languageCode = "en"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

## Hugo Built-in Features
disqusShortname = "diabeticsbc"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

## Permalinks
[permalinks]
    post = "/:slug/"

## ## Site Settings
[params]
    author = "Stuart Hertzog"
    description = "We Are People With Diabetes"
    authorimage = "/img/diabc-logo.png"
    dateformat = "January 2, 2006"
    highlightjs = true
    email = "info@diabeticsbc.ca"
    # highlightjsstyle = "github"
    # please choose either GraphComment or Disqus
    # GraphCommentId = "your-graph-comment-id"

## Social Accounts
[params.social]
    # github = "<username>"
    # instagram = "<username>"
    # xing = "<username>"
    # linkedin = "<username>"
    # twitter = "diabeticsbc"
    # facebook = "groups/diabeticsbc"
    # stackoverflow = "<username>"

## Main Menu
[[menu.main]]
    name = "Home"
    weight = 100
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/pages/about/"
[[menu.main]]
    name = "Posts"
    weight = 300
    identifier = "posts"
    url = "/posts/"
 [[menu.main]]
     name = "Pages"
     weight = 400
     identifier = "pages"
     url = "/pages/"
[[menu.main]]
    name = "Contact"
    identifier = "contact"
    weight = 500
    url = "/pages//contact/"
